plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'application'
}

project.logger.lifecycle("Using Minecraft version: ${version}")

application {
	mainClass = "dev.mcbookshelf.mcdata.Extractor"
}

dependencies {
	minecraft "com.mojang:minecraft:${version}"
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

tasks.withType(JavaExec.class).configureEach {
	args = [version]
}
