plugins {
	id 'fabric-loom' version '1.11-SNAPSHOT'
	id 'application'
	id 'java'
}

project.logger.lifecycle("Using Minecraft version: ${version}")

dependencies {
	minecraft "com.mojang:minecraft:${version}"
	mappings loom.officialMojangMappings()
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
	withSourcesJar()
}

application {
	mainClass = project.property("mainClass")
}

tasks.withType(JavaExec.class).configureEach {
	args = [version]
}