name: Run

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      branch:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
      branch:
        type: string
        required: false
        default: v1

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      - uses: fregante/setup-git-user@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 21
      - name: Run Data Generators
        env:
          BRANCH: ${{ inputs.branch }}
          VERSION: ${{ inputs.version }}
        run: |
          chmod +x ./gradlew
          ./gradlew build -Pversion="$VERSION"
          ./gradlew run -Pversion="$VERSION"
          git checkout --orphan temp
          cp -r "generated/$VERSION/"* .
          git clean -fdX
          rm -rf .github/ src/ gradle/ .gitignore .gitattributes build.gradle gradle.properties gradlew gradlew.bat settings.gradle .run
          git add .
          git commit -m "🚀 Update generated contents for $VERSION"

          if [ "$BRANCH" = "legacy" ]; then
            REF="$VERSION"
          else
            REF="$BRANCH/$VERSION"
          fi

          git tag -f "$REF"
          git push origin "refs/tags/$REF" --force
